In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [52]:
df = pd.read_csv(r'C:\Users\HP\Desktop\Desktop\Data_Set\energydata_complete.csv')
df.head(5)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [79]:
#fitting a linear model and calculating the R-Squared
from sklearn.linear_model import LinearRegression

#initiating linear regression model
linear_model = LinearRegression()

#defining predictor and response variable
x = df.T2.values.reshape(-1,1)
y = df.T6.values.reshape(-1,1)

#fitting regression model
linear_model.fit(x,y)

#calculating r2 of regression model
r2 = linear_model.score(x,y)
round(r2,2)

0.64

In [53]:
# Normalising our dataset to common scale and dropping date and lights column
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = df.drop(columns = ['date','lights'])
normalised_df = pd.DataFrame(scaler.fit_transform(df),columns = df.columns)
normalised_df.head(5)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [59]:
from sklearn.model_selection import train_test_split
X = normalised_df.drop(columns = 'Appliances')
Y = normalised_df['Appliances']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state=42)
x_test

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
8980,0.432946,0.230529,0.120669,0.525822,0.256730,0.380122,0.419820,0.279129,0.312470,0.322900,...,0.457856,0.408251,0.217578,0.920930,0.846491,0.166667,0.953846,0.298643,0.512428,0.512428
2754,0.538543,0.717641,0.377272,0.700066,0.368339,0.956224,0.489489,0.567933,0.224346,0.426866,...,0.145682,0.622241,0.247588,0.588372,0.868421,0.214286,0.400000,0.352941,0.469466,0.469466
9132,0.485744,0.233281,0.111461,0.564252,0.371109,0.300670,0.467568,0.260350,0.408027,0.157503,...,0.468262,0.377621,0.167203,0.858140,0.776316,0.142857,0.984615,0.190045,0.002761,0.002761
14359,0.485744,0.385561,0.566271,0.404255,0.401573,0.381679,0.656757,0.323346,0.411212,0.202260,...,0.561915,0.388797,0.445338,0.895349,0.616228,0.369048,0.600000,0.466817,0.205799,0.205799
8875,0.335093,0.223007,0.026411,0.552910,0.232635,0.356753,0.374775,0.311851,0.244625,0.288467,...,0.427680,0.477373,0.145766,0.938372,0.912281,0.285714,0.735897,0.233032,0.215015,0.215015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,0.560718,0.300248,0.370487,0.412504,0.386895,0.576414,0.608709,0.488263,0.264692,0.304506,...,0.312175,0.507726,0.220257,0.841860,0.756579,0.107143,0.430769,0.251131,0.910115,0.910115
10993,0.518479,0.310063,0.225345,0.593214,0.481888,0.446799,0.464865,0.495092,0.446249,0.264410,...,0.561915,0.528422,0.439443,0.422093,0.651316,0.583333,0.600000,0.486425,0.975531,0.975531
11761,0.436818,0.340611,0.188999,0.633705,0.381356,0.403490,0.422523,0.453692,0.378404,0.230779,...,0.490114,0.356926,0.392283,0.665504,0.796053,0.083333,0.969231,0.515083,0.792703,0.792703
12364,0.550158,0.390973,0.334383,0.602774,0.481888,0.468453,0.576577,0.554702,0.503583,0.237746,...,0.620881,0.417770,0.494105,0.545736,0.596491,0.642857,0.600000,0.520362,0.608307,0.608307
11863,0.432946,0.420145,0.213230,0.688912,0.365570,0.482474,0.414414,0.589273,0.378404,0.243810,...,0.479709,0.507726,0.583065,0.530620,0.734649,0.500000,0.505128,0.740573,0.198911,0.198911

In [80]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)
predicted_values = linear_model.predict(x_test) # independent variable
predicted_values

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [63]:
#MEAN ABSOLUTE ERROR 
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae,2)

0.05

In [71]:
#RESIDUAL SUM OF SQUARES
import statsmodels.api as sm
x_constant = sm.add_constant(predicted_values)
model = sm.OLS(y_test, x_constant).fit()
model.ssr

45.333492032478574

In [87]:
#ROOT MEAN SQUARE ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

In [72]:
#COEFFICIENT OF DETERMINATION
from sklearn.metrics import r2_score
r2_score = r2_score(y_test,predicted_values)
round(r2_score,2)

0.15

In [81]:
linear_model.coef_

array([-0.00328105,  0.5535466 , -0.23617792, -0.45669795,  0.29062714,
        0.09604827,  0.028981  ,  0.02638578, -0.01565684,  0.01600579,
        0.23642491,  0.03804865,  0.01031878, -0.04461364,  0.10199505,
       -0.15759548, -0.18994077, -0.03980032, -0.32185967,  0.00683933,
       -0.07767065,  0.02918313,  0.01230661,  0.11775773,  0.0007701 ,
        0.0007701 ])

In [74]:
def get_weights_df(model, feat,col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [82]:
#OBTAINING THE FEATURE WEIGHT OF LINEAR MODEL
linear_model_weights = get_weights_df(linear_model,x_train,"Linear_Model_Weight")
linear_model_weights

       Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv1             0.000770
11          rv2             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

In [93]:
#TRAINING A RIDGE REGRESSION MODEL WITH AN ALPHA VALUE OF 0.4
from sklearn.linear_model import Ridge
rr = Ridge(alpha = 0.4)
rr.fit(x_train, y_train)
predicted_values_ridge = rr.predict(x_test)

rmse_ridge = np.sqrt(mean_squared_error(y_test, predicted_values_ridge))
round(rmse_ridge, 3)

0.088

In [97]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 0.001)
lasso.fit(x_train, y_train)
predicted_values_lasso = lasso.predict(x_test)

lasso_weight_df = get_weights_df(lasso, x_train, 'Lasso_weight')
lasso_weight_df
# answer: just 4 non zero weights.

       Features  Lasso_weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

In [98]:
#New RMSE with lasso Regression
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_lasso))
round(rmse, 3)

0.094